### ISSUE TITLE
I'm new to graphsage. Can't run. Getting error.Please explain

### ISSUE THREAD

**Issue by tasmimul-huda** [williamleif/GraphSAGE#194]
I'm running the command and got the error ` python -m graphsage.supervised_train --train_prefix toy-ppi  ./example_data/ppi --model graphsage_mean --sigmoid`
Loading training data..
**Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/notebooks/graphsage/supervised_train.py", line 339, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/notebooks/graphsage/supervised_train.py", line 334, in main
    train_data = load_data(FLAGS.train_prefix)
  File "graphsage/utils.py", line 20, in load_data
    G_data = json.load(open(prefix + "-G.json"))
IOError: [Errno 2] No such file or directory: 'toy-ppi-G.json'**

**Comment by ShreyashUke** [comment]
Try running this command python -m graphsage.supervised_train --train_prefix ./example_data/toy-ppi --model graphsage_mean --sigmoid
