### ISSUE TITLE
why i still can't run the program because an error No such file or directory: './example_data/ppi-G.json'

### ISSUE THREAD

**Issue by madewijayya** [williamleif/GraphSAGE#199]
IOError: [Errno 2] No such file or directory: './example_data/ppi-G.json'
root@9351d38c244b:/notebooks# sh example_unsupervised.sh
Loading training data..
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/notebooks/graphsage/unsupervised_train.py", line 383, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/notebooks/graphsage/unsupervised_train.py", line 378, in main
    train_data = load_data(FLAGS.train_prefix, load_walks=True)
  File "graphsage/utils.py", line 20, in load_data
    G_data = json.load(open(prefix + "-G.json"))
IOError: [Errno 2] No such file or directory: './example_data/ppi-G.json'

**Comment by brainplait** [comment]
Please note that the data file in the code is toy-ppi-G.json. The command I ran was “python -m graphsage.supervised_train --train_prefix ./example_data/toy-ppi --model graphsage_mean --sigmoid”。
